backtraces_path = "/users/Zeb/neovide_backtraces.log" # see below for the default platform specific location
fork = true
frame = "none"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = false # platform-specific: false (Linux/macOS) or true (Windows)
tabs = false
title-hidden = true
vsync = true
wsl = false
neovim_bin = "/opt/homebrew/bin/nvim"

[font]
normal = "Liga SFMono Nerd Font"
size = 13.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes
