## Base16 Harmonic16 Dark
# Author: Jannik Siebert (https://github.com/janniks)
[general]
background = "#0b1c2c"
border = "#f7f9fb"
horizontal_rule = "#405c79"
unread_indicator = "#8bbf56"

[text]
primary = "#cbd6e2"
secondary = "#aabcce"
tertiary = "#8bbf56"
success = "#56bf8b"
error = "#bf8b56"

[buffer]
action = "#56bf8b"
background = "#0b1c2c"
background_text_input = "#223b54"
background_title_bar = "#223b54"
border = "#627e99"
border_selected = "#f7f9fb"
code = "#bf568b"
highlight = "#223b54"
nickname = "#568bbf"
selection = "#405c79"
timestamp = "#cbd6e2"
topic = "#aabcce"
url = "#8b56bf"

[buffer.server_messages]
join = "#56bf8b"
part = "#bf8b56"
quit = "#bf8b56"
default = "#568bbf"

[buttons.primary]
background = "#0b1c2c"
background_hover = "#405c79"
background_selected = "#405c79"
background_selected_hover = "#627e99"

[buttons.secondary]
background = "#223b54"
background_hover = "#405c79"
background_selected = "#405c79"
background_selected_hover = "#627e99"
