## Base16 Atelier Sulphurpool
# Author: Bram de Haan (http://atelierbramdehaan.nl)
[general]
background = "#202746"
border = "#f5f7ff"
horizontal_rule = "#5e6687"
unread_indicator = "#c08b30"

[text]
primary = "#979db4"
secondary = "#898ea4"
tertiary = "#c08b30"
success = "#ac9739"
error = "#c94922"

[buffer]
action = "#ac9739"
background = "#202746"
background_text_input = "#293256"
background_title_bar = "#293256"
border = "#6b7394"
border_selected = "#f5f7ff"
code = "#6679cc"
highlight = "#293256"
nickname = "#22a2c9"
selection = "#5e6687"
timestamp = "#979db4"
topic = "#898ea4"
url = "#3d8fd1"

[buffer.server_messages]
join = "#ac9739"
part = "#c94922"
quit = "#c94922"
default = "#22a2c9"

[buttons.primary]
background = "#202746"
background_hover = "#5e6687"
background_selected = "#5e6687"
background_selected_hover = "#6b7394"

[buttons.secondary]
background = "#293256"
background_hover = "#5e6687"
background_selected = "#5e6687"
background_selected_hover = "#6b7394"
