## Base16 Gruvbox Material Light, Hard
# Author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
[general]
background = "#f9f5d7"
border = "#282828"
horizontal_rule = "#e0cfa9"
unread_indicator = "#b47109"

[text]
primary = "#654735"
secondary = "#c9b99a"
tertiary = "#b47109"
success = "#6c782e"
error = "#c14a4a"

[buffer]
action = "#6c782e"
background = "#f9f5d7"
background_text_input = "#fbf1c7"
background_title_bar = "#fbf1c7"
border = "#a89984"
border_selected = "#282828"
code = "#945e80"
highlight = "#fbf1c7"
nickname = "#4c7a5d"
selection = "#e0cfa9"
timestamp = "#654735"
topic = "#c9b99a"
url = "#45707a"

[buffer.server_messages]
join = "#6c782e"
part = "#c14a4a"
quit = "#c14a4a"
default = "#4c7a5d"

[buttons.primary]
background = "#f9f5d7"
background_hover = "#e0cfa9"
background_selected = "#e0cfa9"
background_selected_hover = "#a89984"

[buttons.secondary]
background = "#fbf1c7"
background_hover = "#e0cfa9"
background_selected = "#e0cfa9"
background_selected_hover = "#a89984"
