## Base16 Black Metal (Bathory)
# Author: metalelf0 (https://github.com/metalelf0)
[general]
background = "#000000"
border = "#c1c1c1"
horizontal_rule = "#222222"
unread_indicator = "#e78a53"

[text]
primary = "#c1c1c1"
secondary = "#999999"
tertiary = "#e78a53"
success = "#fbcb97"
error = "#5f8787"

[buffer]
action = "#fbcb97"
background = "#000000"
background_text_input = "#121212"
background_title_bar = "#121212"
border = "#333333"
border_selected = "#c1c1c1"
code = "#999999"
highlight = "#121212"
nickname = "#aaaaaa"
selection = "#222222"
timestamp = "#c1c1c1"
topic = "#999999"
url = "#888888"

[buffer.server_messages]
join = "#fbcb97"
part = "#5f8787"
quit = "#5f8787"
default = "#aaaaaa"

[buttons.primary]
background = "#000000"
background_hover = "#222222"
background_selected = "#222222"
background_selected_hover = "#333333"

[buttons.secondary]
background = "#121212"
background_hover = "#222222"
background_selected = "#222222"
background_selected_hover = "#333333"
