## Base16 Nord
# Author: arcticicestudio
[general]
background = "#2e3440"
border = "#8fbcbb"
horizontal_rule = "#434c5e"
unread_indicator = "#ebcb8b"

[text]
primary = "#e5e9f0"
secondary = "#d8dee9"
tertiary = "#ebcb8b"
success = "#a3be8c"
error = "#bf616a"

[buffer]
action = "#a3be8c"
background = "#2e3440"
background_text_input = "#3b4252"
background_title_bar = "#3b4252"
border = "#4c566a"
border_selected = "#8fbcbb"
code = "#b48ead"
highlight = "#3b4252"
nickname = "#88c0d0"
selection = "#434c5e"
timestamp = "#e5e9f0"
topic = "#d8dee9"
url = "#81a1c1"

[buffer.server_messages]
join = "#a3be8c"
part = "#bf616a"
quit = "#bf616a"
default = "#88c0d0"

[buttons.primary]
background = "#2e3440"
background_hover = "#434c5e"
background_selected = "#434c5e"
background_selected_hover = "#4c566a"

[buttons.secondary]
background = "#3b4252"
background_hover = "#434c5e"
background_selected = "#434c5e"
background_selected_hover = "#4c566a"
