## Base16 Google Light
# Author: Seth Wright (http://sethawright.com)
[general]
background = "#ffffff"
border = "#1d1f21"
horizontal_rule = "#c5c8c6"
unread_indicator = "#fba922"

[text]
primary = "#373b41"
secondary = "#969896"
tertiary = "#fba922"
success = "#198844"
error = "#cc342b"

[buffer]
action = "#198844"
background = "#ffffff"
background_text_input = "#e0e0e0"
background_title_bar = "#e0e0e0"
border = "#b4b7b4"
border_selected = "#1d1f21"
code = "#a36ac7"
highlight = "#e0e0e0"
nickname = "#3971ed"
selection = "#c5c8c6"
timestamp = "#373b41"
topic = "#969896"
url = "#3971ed"

[buffer.server_messages]
join = "#198844"
part = "#cc342b"
quit = "#cc342b"
default = "#3971ed"

[buttons.primary]
background = "#ffffff"
background_hover = "#c5c8c6"
background_selected = "#c5c8c6"
background_selected_hover = "#b4b7b4"

[buttons.secondary]
background = "#e0e0e0"
background_hover = "#c5c8c6"
background_selected = "#c5c8c6"
background_selected_hover = "#b4b7b4"
