## Base16 Tokyo Night Terminal Storm
# Author: MichaÃ«l Ball
[general]
background = "#24283b"
border = "#d5d6db"
horizontal_rule = "#343a52"
unread_indicator = "#e0af68"

[text]
primary = "#787c99"
secondary = "#787c99"
tertiary = "#e0af68"
success = "#41a6b5"
error = "#f7768e"

[buffer]
action = "#41a6b5"
background = "#24283b"
background_text_input = "#1a1b26"
background_title_bar = "#1a1b26"
border = "#444b6a"
border_selected = "#d5d6db"
code = "#bb9af7"
highlight = "#1a1b26"
nickname = "#7dcfff"
selection = "#343a52"
timestamp = "#787c99"
topic = "#787c99"
url = "#7aa2f7"

[buffer.server_messages]
join = "#41a6b5"
part = "#f7768e"
quit = "#f7768e"
default = "#7dcfff"

[buttons.primary]
background = "#24283b"
background_hover = "#343a52"
background_selected = "#343a52"
background_selected_hover = "#444b6a"

[buttons.secondary]
background = "#1a1b26"
background_hover = "#343a52"
background_selected = "#343a52"
background_selected_hover = "#444b6a"
