## Base16 Sandcastle
# Author: George Essig (https://github.com/gessig)
[general]
background = "#282c34"
border = "#fdf4c1"
horizontal_rule = "#3e4451"
unread_indicator = "#a07e3b"

[text]
primary = "#a89984"
secondary = "#928374"
tertiary = "#a07e3b"
success = "#528b8b"
error = "#83a598"

[buffer]
action = "#528b8b"
background = "#282c34"
background_text_input = "#2c323b"
background_title_bar = "#2c323b"
border = "#665c54"
border_selected = "#fdf4c1"
code = "#d75f5f"
highlight = "#2c323b"
nickname = "#83a598"
selection = "#3e4451"
timestamp = "#a89984"
topic = "#928374"
url = "#83a598"

[buffer.server_messages]
join = "#528b8b"
part = "#83a598"
quit = "#83a598"
default = "#83a598"

[buttons.primary]
background = "#282c34"
background_hover = "#3e4451"
background_selected = "#3e4451"
background_selected_hover = "#665c54"

[buttons.secondary]
background = "#2c323b"
background_hover = "#3e4451"
background_selected = "#3e4451"
background_selected_hover = "#665c54"
