## Base16 Material Darker
# Author: Nate Peterson
[general]
background = "#212121"
border = "#ffffff"
horizontal_rule = "#353535"
unread_indicator = "#ffcb6b"

[text]
primary = "#eeffff"
secondary = "#b2ccd6"
tertiary = "#ffcb6b"
success = "#c3e88d"
error = "#f07178"

[buffer]
action = "#c3e88d"
background = "#212121"
background_text_input = "#303030"
background_title_bar = "#303030"
border = "#4a4a4a"
border_selected = "#ffffff"
code = "#c792ea"
highlight = "#303030"
nickname = "#89ddff"
selection = "#353535"
timestamp = "#eeffff"
topic = "#b2ccd6"
url = "#82aaff"

[buffer.server_messages]
join = "#c3e88d"
part = "#f07178"
quit = "#f07178"
default = "#89ddff"

[buttons.primary]
background = "#212121"
background_hover = "#353535"
background_selected = "#353535"
background_selected_hover = "#4a4a4a"

[buttons.secondary]
background = "#303030"
background_hover = "#353535"
background_selected = "#353535"
background_selected_hover = "#4a4a4a"
