## Base16 Zenburn
# Author: elnawe
[general]
background = "#383838"
border = "#ffffff"
horizontal_rule = "#606060"
unread_indicator = "#e0cf9f"

[text]
primary = "#dcdccc"
secondary = "#808080"
tertiary = "#e0cf9f"
success = "#5f7f5f"
error = "#dca3a3"

[buffer]
action = "#5f7f5f"
background = "#383838"
background_text_input = "#404040"
background_title_bar = "#404040"
border = "#6f6f6f"
border_selected = "#ffffff"
code = "#dc8cc3"
highlight = "#404040"
nickname = "#93e0e3"
selection = "#606060"
timestamp = "#dcdccc"
topic = "#808080"
url = "#7cb8bb"

[buffer.server_messages]
join = "#5f7f5f"
part = "#dca3a3"
quit = "#dca3a3"
default = "#93e0e3"

[buttons.primary]
background = "#383838"
background_hover = "#606060"
background_selected = "#606060"
background_selected_hover = "#6f6f6f"

[buttons.secondary]
background = "#404040"
background_hover = "#606060"
background_selected = "#606060"
background_selected_hover = "#6f6f6f"
