## Base16 Bright
# Author: Chris Kempson (http://chriskempson.com)
[general]
background = "#000000"
border = "#ffffff"
horizontal_rule = "#505050"
unread_indicator = "#fda331"

[text]
primary = "#e0e0e0"
secondary = "#d0d0d0"
tertiary = "#fda331"
success = "#a1c659"
error = "#fb0120"

[buffer]
action = "#a1c659"
background = "#000000"
background_text_input = "#303030"
background_title_bar = "#303030"
border = "#b0b0b0"
border_selected = "#ffffff"
code = "#d381c3"
highlight = "#303030"
nickname = "#76c7b7"
selection = "#505050"
timestamp = "#e0e0e0"
topic = "#d0d0d0"
url = "#6fb3d2"

[buffer.server_messages]
join = "#a1c659"
part = "#fb0120"
quit = "#fb0120"
default = "#76c7b7"

[buttons.primary]
background = "#000000"
background_hover = "#505050"
background_selected = "#505050"
background_selected_hover = "#b0b0b0"

[buttons.secondary]
background = "#303030"
background_hover = "#505050"
background_selected = "#505050"
background_selected_hover = "#b0b0b0"
