## Base16 Pasque
# Author: Gabriel Fontes (https://github.com/Misterio77)
[general]
background = "#271c3a"
border = "#bbaadd"
horizontal_rule = "#3e2d5c"
unread_indicator = "#804ead"

[text]
primary = "#dedcdf"
secondary = "#bebcbf"
tertiary = "#804ead"
success = "#c6914b"
error = "#a92258"

[buffer]
action = "#c6914b"
background = "#271c3a"
background_text_input = "#100323"
background_title_bar = "#100323"
border = "#5d5766"
border_selected = "#bbaadd"
code = "#953b9d"
highlight = "#100323"
nickname = "#7263aa"
selection = "#3e2d5c"
timestamp = "#dedcdf"
topic = "#bebcbf"
url = "#8e7dc6"

[buffer.server_messages]
join = "#c6914b"
part = "#a92258"
quit = "#a92258"
default = "#7263aa"

[buttons.primary]
background = "#271c3a"
background_hover = "#3e2d5c"
background_selected = "#3e2d5c"
background_selected_hover = "#5d5766"

[buttons.secondary]
background = "#100323"
background_hover = "#3e2d5c"
background_selected = "#3e2d5c"
background_selected_hover = "#5d5766"
