[general]
background = "#12111E"
border = "#1D1F27"
horizontal_rule = "#44475A"
unread_indicator = "#6272A4"

[text]
primary = "#F8F8F2"
secondary = "#72778E"
tertiary = "#BD93FA"
success = "#50FA7B"
error = "#FF5555"

[buffer]
action = "#FFB86C"
background = "#27273DE2"
background_text_input = "#1A1B24"
background_title_bar = "#3C3A5C"
border = "#00000000"
border_selected = "#50FA7B"
code = "#FF79C6"
highlight = "#2B2E3A"
nickname = "#FF79C6"
selection = "#353947"
timestamp = "#C5B15CAA"
topic = "#6DF7F5"
url = "#8BE9FD"

  [buffer.server_messages]
  join = "#242424B4"
  default = "#F1FA8C"

[buttons.primary]
background = "#443966"
background_hover = "#282A36"
background_selected = "#746290"
background_selected_hover = "#313141"

[buttons.secondary]
background = "#2B2E3A"
background_hover = "#323644"
background_selected = "#3B364E"
background_selected_hover = "#564A72"
